motor_book/books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("", views.MainView.as_view()),
    path("homepage.html", views.BookListView.as_view(), name="home"),
    path("car_list/<slug:slug>", views.car_list, name="car_list"),
    path(
        "category_list/<slug:slug>", views.category_list, name="category_list"
    ),
    path("book/<slug:slug>/", views.book_detail, name="book_detail"),
]

motor_book/motor_book/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("books.urls", namespace="books")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

motor_book/templates/includes/footer.html
{% load static %}
<footer>
    © 2014 - {% now "Y" %} Издательство "МОТОР". Все права защищены.
</footer>

motor_book/templates/includes/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>

<body>
    <div class="page-wrapper">
        <header>
            <nav>
                <div class="navbar">
                    <div class="nav-header">
                        <img src="{% static 'img/logo-motor.svg' %}" alt="logo" class="logo">
                        <div class="nav-toggle">
                            <input type="checkbox"></input>
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>
                    <ul class="menu">
                        <li><a href="{% url 'books:home' %}">HOME</a></li>
                        <li><a href="#order">ORDER</a></li>
                        <li><a href="#payment">PAYMENT & SHIPPING</a></li>
                        <li><a href="#pricelist">PRICELIST</a></li>
                        <li><a href="#contact">CONTACT</a></li>
                    </ul>
                </div>
            </nav>
        </header>


</html>

motor_book/templates/includes/header1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>

</html>